#!/bin/sh
set -e
echo '### Optimizing resources ###'
tools/run_optimize
echo '### Modifying cache.manifest ###'
sed -i '' "s/^#.*/# `date`/" cache.manifest
echo '### Commit and push ###'
git commit -a -m "Prepare deployment"
git branch -f gh-pages master
git push --all
