#!/bin/sh
set -e
echo '### Optimizing resources ###'
scripts/run_optimize
echo '### Modifying cache.manifest ###'
sed -i "s/^#.*$/# `date`/g" cache.manifest
echo '### Commit and push ###'
git commit -a -m "Prepare deployment"
git checkout gh-pages
git merge master
git checkout master
git push --all